config/routes.rb
Myapp1::Application.routes.draw do
  resources :reserves

  resources :rooms

  resources :users

  resources :addresses

     match 'disp' => 'bookings#show'

end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserf.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reserves }
    end
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
    @reserf = Reserf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reserf }
    end
  end

  # GET /reserves/new
  # GET /reserves/new.json
  def new
    @reserf = Reserf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reserf }
    end
  end

  # GET /reserves/1/edit
  def edit
    @reserf = Reserf.find(params[:id])
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserf.new(params[:reserf])

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Reserf was successfully created.' }
        format.json { render json: @reserf, status: :created, location: @reserf }
      else
        format.html { render action: "new" }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reserves/1
  # PUT /reserves/1.json
  def update
    @reserf = Reserf.find(params[:id])

    respond_to do |format|
      if @reserf.update_attributes(params[:reserf])
        format.html { redirect_to @reserf, notice: 'Reserf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf = Reserf.find(params[:id])
    @reserf.destroy

    respond_to do |format|
      format.html { redirect_to reserves_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= form_for(@reserf) do |f| %>
  <% if @reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% @reserf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br />
    <%= f.text_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :reserve_day %><br />
    <%= f.datetime_select :reserve_day %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br />
    <%= f.text_field :timezone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserves/edit.html.erb
<h1>Editing reserf</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/index.html.erb
<h1>Listing reserves</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Room</th>
    <th>Reserve day</th>
    <th>Timezone</th>
    <th>User</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reserves.each do |reserf| %>
  <tr>
    <td><%= reserf.id %></td>
    <td><%= reserf.room_id %></td>
    <td><%= reserf.reserve_day %></td>
    <td><%= reserf.timezone %></td>
    <td><%= reserf.user_id %></td>
    <td><%= reserf.name %></td>
    <td><%= link_to 'Show', reserf %></td>
    <td><%= link_to 'Edit', edit_reserf_path(reserf) %></td>
    <td><%= link_to 'Destroy', reserf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reserf', new_reserf_path %>

app/views/reserves/new.html.erb
<h1>New reserf</h1>

<%= render 'form' %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @reserf.id %>
</p>

<p>
  <b>Room:</b>
  <%= @reserf.room_id %>
</p>

<p>
  <b>Reserve day:</b>
  <%= @reserf.reserve_day %>
</p>

<p>
  <b>Timezone:</b>
  <%= @reserf.timezone %>
</p>

<p>
  <b>User:</b>
  <%= @reserf.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @reserf.name %>
</p>


<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>